/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ch_bfh_bachelor_opengl_JNIOpenGLInterface */

#ifndef _Included_ch_bfh_bachelor_opengl_JNIOpenGLInterface
#define _Included_ch_bfh_bachelor_opengl_JNIOpenGLInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ch_bfh_bachelor_opengl_JNIOpenGLInterface
 * Method:    init
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_ch_bfh_bachelor_opengl_JNIOpenGLInterface_init
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     ch_bfh_bachelor_opengl_JNIOpenGLInterface
 * Method:    step
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ch_bfh_bachelor_opengl_JNIOpenGLInterface_step
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
